### ISSUE TITLE
CiviGrant Report Template: Add reviewer first name and last name

### ISSUE THREAD

**Issue by ejodlowska** [python/psfmemberdotorg#8]
Hey @MarkMangoba  - right now the grants report template does not include the fields for reviewer. It would be great if we can add the two fields in addition to the notes field, which is already there...see screen shot. 

This way I can have a report of which entity is responsible for which grant
<img width="1198" alt="screen shot 2017-08-15 at 8 12 00 am" src="https://user-images.githubusercontent.com/2590029/29317481-bb5f0d90-8191-11e7-8693-bba9c36a61fa.png">

**Comment by MarkMangoba** [comment]
@ejodlowska added Last Name | First Name | E-Mail
