### ISSUE TITLE
CiviGrant:  Require a US intermediary SWIFT code for any international wire transfer

### ISSUE THREAD

**Issue by PhyllisDobbs** [python/psfmemberdotorg#9]
Add a line for international wire instructions that requires a US intermediary SWIFT code.

Reason:  certain wire transfers have been failing due to lack of a US intermediary SWIFT code.  SunTrust indicated that all international wire transfers require a US intermediary, which SunTrust sometimes populates.  SunTrust does not have a lookup table between international and US intermediary SWIFT codes.

**Comment by MarkMangoba** [comment]
@PhyllisDobbs essentially, just to clarify, this action would be when the user selects WIRE for disbursement?

**Comment by PhyllisDobbs** [comment]
Yes, that is correct.  We do not need this action for PayPal or check.

Thanks,

Phyllis A. Dobbs
Controller
Python Software Foundation

**Comment by MarkMangoba** [comment]
completed when:  Disbursement * = wire
US intermediary SWIFT code *
